### ISSUE TITLE
Support for ignoring resources

### ISSUE THREAD

**Issue by kraifpatrik** [GameMakerHub/Catalyst#20]
It would be handy to be able to specify resources or resource folders that we don't want to include in the package, kinda like git has .gitignore, but maybe this could be stored directly in the catalyst.json file.

**Examples:**
`catalyst ignore "scr_config_local"` => ignore script "scr_config_local"
`catalyst ignore "test/*"` => ignore resources inside folders called "test"
`catalyst ignore "_*"` => ignore files starting with "_"

**Comment by RobQuistNL** [comment]
Working on this in the master branch right now. Not functional yet :) will be soon.

**Comment by RobQuistNL** [comment]
This feature has been added to the master branch - will do a new release containing this feature soon.
