### ISSUE TITLE
Catalyst - git integration issue

### ISSUE THREAD

**Issue by Katipo007** [GameMakerHub/Catalyst#22]
When switching devices (thus working with a different local copy of the git repository) and running `catalyst install` to have the vendor files installed for this local copy fails, producing the error:
```
In StorageService.php line 48:

File does not exist or is not a file: C:/<path>/views/<viewId>.yy

install [-d|--dry-run]
```

It cannot find this file because it was added to the `.gitignore` by catalyst and so wasn't in the repository to pull to the local copy.

The suggested `catalyst install --dry-run` produces the same error.

Version 0.2.0-alpha

**Comment by RobQuistNL** [comment]
Does that `.gitignore` file contain full pathnames? IIRC it should contain local path names and thus shouldn't be an issue. What OS are you using?

**Comment by Katipo007** [comment]
OS: Windows 10

Pathnames in the `.gitignore` are relative:
```
...
scripts/pulse
scripts/color_lerp
views/86336395-3fd9-67e2-0521-61854eb28499.yy
...
```

**Comment by RobQuistNL** [comment]
Thanks! I'l see if I can reproduce this soon.

**Comment by RobQuistNL** [comment]
Ah! Nice find. I've been able to reproduce it - I've added a "stray resource" check in quite late, but this is conflicting. I'll be writing tests for both the issues you've submitted, for now I've got 2 MR's ready with the fixes.
